baseURL = 'https://mainline4lumia.github.io'
languageCode = 'en-us'
title = 'Mainline4Lumia'
description = 'Bringing Mainline Linux to your Lumias!'
theme = "PaperMod"
paginate = 5

[params]
  mainSections = ["posts"]

  title = "Mainline4Lumia"
  description = "Bringing Mainline Linux to your Lumias!"
  images = [ "https://avatars.githubusercontent.com/u/86826507" ]

  defaultTheme = "dark"
  hideFooter = true

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"

  [params.profileMode]
    enabled = true
    title = "Mainline4Lumia"
    subtitle = "Bringing Mainline Linux to your Lumias!"
    imageUrl = "https://avatars.githubusercontent.com/u/86826507"
    imageWidth = 240
    imageHeight = 240
    imageTitle = "Mainline4Lumia"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Mainline4Lumia/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "devices"
    name = "Devices"
    url = "/devices/"
    weight = 2

