baseURL = 'https://mainline4lumia.github.io'
languageCode = 'en-us'
title = 'Mainline4Lumia'
description = 'Bringing Mainline Linux to your Lumias!'
theme = "PaperMod"
paginate = 5

[params]
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "devices"
    name = "Devices"
    url = "/devices/"
    weight = 2