baseURL = 'https://mainline4lumia.github.io'
languageCode = 'en-us'
title = 'Mainline4Lumia'
description = 'Bringing Mainline Linux to your Lumias!'
theme = "paper"

[params]
  github = 'Mainline4Lumia'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
